### PR TITLE
feat: add `enable` option

### PR DESCRIPTION
**Pull request by vencho-mdp**
Hi! This would be useful to disable the module in dev.

### CODE REVIEW

**Comment by ijkml** [comment]
Yes, thank you! Great work!

**Comment by ijkml** [comment]
This line https://github.com/ijkml/nuxt-umami/blob/6c55affac472e776597ee58d5397dcac1c6851c2/src/module.ts#L42 sets umami to undefined everywhere it is used which makes sense. We would have to move it someplace else, prevent loading the script instead.

**Comment by vencho-mdp** [comment]
Oh, that's certainly true. Maybe it should not load the script, but the types should be imported (thus, providing good DX). WDYT?

**Comment by ijkml** [comment]
Yes, I think that should work here:
https://github.com/ijkml/nuxt-umami/blob/main/src/runtime/plugin-3.ts#L39

**Comment by vencho-mdp** [comment]
Alright! I messed around a little bit with git but now it should be OK.

**Comment by ijkml** [comment]
$umami is undefined again... Is it working there?
I think it is because we're exiting early before the mockFunction is declared.

**Comment by vencho-mdp** [comment]
That's true. My bad.

**Comment by ijkml** [comment]
No biggie :v: 
Can I commit to your repo/branch? I feel we should also add a helpful warning when the module is disabled.

**Comment by ijkml** [comment]
I think it now works as expected :laughing:
What do you think?

**Comment by vencho-mdp** [comment]
I completely agree!

**Comment by ijkml** [comment]
It is part of the script options. Up to this point, it was simply ignored. Found that out thanks to you!

**Pull request merged**
