### PR TITLE
feat: compatibility with Umami v2

### PR DESCRIPTION
**Pull request by tmlmt**
### Linked Issue 

#52 

### Description

Adds compatibility with Umami v2, without breaking changes. 

As this package doesn't check html elements for the `data-umami-event-*` attributes (it used to be CSS classes in v1) and doesn't address all the data visualisation features of umami (managing websites / users / teams, and getting stats) which has also been subject to new API endpoints in v2, the edits were pretty straight-forward.

The main changes introduced in v2 and that needed to be taken into account were:
- change in API endpoint: `/api/send` instead of `/api/collect`
- page `title` is also tracked
- change in request structure to the API: all API calls should now have `type: event` (see https://github.com/umami-software/umami/issues/1933) 
  - when property `name` is omitted, the payload will be considered as a page view
  - when property `name` is set, the payload will be considered as an event, and event data can be passed in property `data`

The playground has also been slightly edited by adding a `title` to each page

### CODE REVIEW

**Comment by ijkml** [comment]
Hey @tmlmt, thanks for this! I'll review/add as necessary. Thank you.

**Comment by ijkml** [comment]
Hey @tmlmt 4 hours later and a mammoth update, but here's the gist:

- I don't know of any easy/straightforward way to make `document.title` reactive. So, I am using `useTitle` from VueUse.
- Auto track now needs to happen after page change. We could use a navigation hook `router.afterEach` or Nuxt's `page:finish` hook. I went with the latter, and set up the hook in a Nuxt plugin.
- Auto track fails to capture the new page's title (:man_shrugging:), something to look into, but setting a timeout (about 300ms) temporarily fixes that. You can try setting the timeout to 0 in [plugins/umami.client.ts](https://github.com/ijkml/nuxt-umami/blob/0b9055dd0ef0c447e7c9e691684df6b13b60f75a/plugins/umami.client.ts#L12) to see what I mean.
- Minor, but Umami 1 has no problem with additional properties in the payload. That affords us to lose some of the `if (version === 2)` checks and simplify types.

**Comment by tmlmt** [comment]
Hey @ijkml! Hehe it seems I kind of forced into Umami v2 :D Thanks a lot for looking into this.

- It seems that both Umami (https://github.com/umami-software/umami/blob/26a9cb67d8cba08da739c0c9ad3394867bc7cba9/tracker/index.js#L155-L167) and vueUse (https://github.com/vueuse/vueuse/blob/295687625292a45ee294ae8ea36e2947a87c1c1a/packages/core/useTitle/index.ts#L73-L91) in their own way, basically observe the `title` dom element using a MutationObserver. We shouldn't reinvent the wheel so I think using the compact way is great i.e. `useTitle` from VueUse as you did :)
- Noted about Umami 1 not complaining about additional properties in the payload, that's good. Great type simplification, although you now have a non-meaningful interface `ViewPayload` (as it extends `BasicPayload` with `{}`) which would throw an error with [@typescript-eslint/no-empty-interface](https://typescript-eslint.io/rules/no-empty-interface/)
- It was elegant to trigger the auto track with a route middleware. Is the fact that we now need to capture the (updated) title the only reason you are going for a plugin and a hook?
- Then, about the auto track failing to capture the new title, if your plugin-way and the `page:finish` hook is the way to go, then using `nextTick` might be a better option than setting an arbitrary timeout? What about the `page:transition:finish` hook? 

Will definitely spend some time exploring this further when I can take the time, but I wanted to share some thoughts already.

**Comment by ijkml** [comment]
Thanks for the push, haha 😅.

- ☑
- Thanks for mentioning that. Was trying to keep the naming consistent, maybe I should do that in exports. Nice.
- Yes, that's the only reason. I liked the route middleware better, but as far as I can tell, it runs before route change, so we can't access the new title.
- Tried both `nextTick` and `page:transition:finish`. The first didn't fix it, and the second... Is the hook only triggered when there IS a transition to run? Didn't work, but I'd definitely try that again.

**Comment by tmlmt** [comment]
Hey @ijkml, no coding yet but I did a bit of digging in the meantime:

- The reason why the `page:finish` hook is not capturing title change, is because the update of head DOM via `useHead()` is triggered by that hook in nuxt, by [calling the `entries:updated`](https://github.com/nuxt/nuxt/blob/c6578219fa6746c82e1ce23746e098bd2b48027f/packages/nuxt/src/head/runtime/plugins/unhead.ts#L19-L26) hook of `unhead`. That hook then [calls a rendering function](https://github.com/unjs/unhead/blob/cba216e4736053ff86edacc1a7fc64ccc5630eca/packages/dom/src/patchDomOnEntryUpdatesPlugin.ts#L12), that we can follow to see that it ends up calling for each rendered tag, the [`dom:renderTag`](https://github.com/unjs/unhead/blob/cba216e4736053ff86edacc1a7fc64ccc5630eca/packages/dom/src/renderDOMHead.ts#L212) hook. That leads me to two questions: 
  - Is that the hook we want to follow? Or are we creating a flow which is dependent on people using Nuxt's built-in composables and components (useHead, useTitle, <Title>) to update the title? Maybe that's fair to expect
  - Or do we want to directly observe `document.title` to know when to trigger the tracker?

- It seems that Nuxt has a built-in `useTitle` (see [VueUse's doc](https://vueuse.org/core/useTitle/)) so we can remove [this import](https://github.com/tmlmt/nuxt-umami/blob/95b6df252351c4703da68211e5875a8d229e5da1/internal/utils.ts#LL1) ?

**Comment by ijkml** [comment]
Great digging! Please don't stop 🙏.

- To answer your questions
    - No, no preference from me. Just need a hook that runs after every route change and gets the correct stuff.
    - We can, but shouldn't. What if every page share the same title (set in `nuxt.config` or layout)? What if none of the pages have a title? I think we might run into issues if we setup autoTrack to depend on title.
- There is no mention of `useTitle` in Nuxt's docs/website, maybe it's deprecated?

**Comment by tmlmt** [comment]
Thanks for your replies! 

- So basically we want every route change to trigger `trackView` if `autoTrack` is enabled, but wait for the title to be updated in the DOM ... if such an update is expected. I am not sure whether I fully understand all the hooks lifecycle of nuxt+unhead. Shall we ask for help from the unhead team to figure out whether there's a good hook we can use? Otherwise I can try to play around in the playground. 
- Indeed, I left a message on Discord to ask if anyone can clarify.

**Comment by ijkml** [comment]
Hey! Sorry for not seeing to this earlier.
- It'd be wonderful if we can find an unhead hook that can do that and that we can use from Nuxt. I agree, we should get help :sweat_smile:.
- Thank you!

**Comment by ijkml** [comment]
Hi @tmlmt 
I found your messages/thread with Harlan. Thank you very much for your help.

I think we should merge and release this pending an answer and possible solution.

I was thinking v3... but not many breaking changes. What do you think?

**Comment by tmlmt** [comment]
Hey @ijkml yeah I saw that you saw ! Was trying to get some expert help, but it might take some time. Sorry I didn't have time at all this week to try out  anything, hope to get a few hours next week.

You're the maintainer so you decide :) my opinion would be:
- When it comes to releasing, although it may not be the most elegant, the timeout works, so the functionality is there. 
- With regards to versioning, in my mind we shift from middleware to plugin but there's no breaking change, you're just adding a feature and are still providing things as a nuxt layer. So a minor release would sound fine. I was actually thinking about a v3 for another reason but I can explore a bit the idea and open a post in the Discussions section to discuss that.

**Comment by ijkml** [comment]
Alright, @tmlmt. Many thanks for your work.

**Pull request merged**
