### PR TITLE
feat: new directive, `v-umami`

### PR DESCRIPTION
**Pull request by Velka-DEV**
As mentionned here: #60 

I start this PR to add the data attributes events tracking introduced in umami v2 (in fact as the nuxt-umami library don't act anymore as a simple script loader since v2, this should work correctly with umami v1)

@ijkml In the code you will find three points where i prefer to discuss with you before implementing anything.

1: `TODO: Introduce a new setting for auto event tracking` 

2: `TODO: We should introduce a new setting to allow users to change the 'umami' keyword, this may help bypass adblockers in the future`

3: `TODO: Think about handling multiple events (e.g. click, focus, etc.) (Maybe using an attribute like data-umami-type="click focus") `

### CODE REVIEW

**Comment by ijkml** [comment]
Hey @Velka-DEV, I'm really sorry for taking forever to respond.

1: Something like `trackAttributes` or `trackAttrs` should work, but I'm open to ideas.
2: In light of this, we can make `trackAttrs` an object. `{enable: boolean = false, attrName: string = 'umami'}`
3: That's interesting, however I don't think I fully understand the use cases. Please clarify :pray:.

**Comment by ijkml** [comment]
Your implementation is great; however, there is a slight problem. For example, when elements are toggled on/off they stop tracking. I'd guess buttons on new pages would fail to track too, since we're fetching all elements on `app:mounted`. You can see it in the demo I just pushed.

I think a Mutation Observer would solve that problem.

**Comment by ijkml** [comment]
On the other hand, I'm thinking of introducing a directive (not as a replacement for attributes).

```vue
<!-- Just event name -->
<button v-umami="'eventName'">Track</button>

<!-- Event name and data (data is separate object) -->
<button v-umami="{name: 'eventName', data: {}}" />

<!-- or maybe name and data in same object -->
<button v-umami="{name: 'eventName', id: 2, email: 'email@email.com' }" />
```

But, functions, attributes, and directives might just be too much... What do you think?

**Comment by Velka-DEV** [comment]
Hey @ijkml, 

It's a very good idea, and indeed both types of tracking would be too much. I much prefer your proposal. 

Will you take care of the implementation, or shall I? I'll probably have time during the week to take care of it.

**Comment by ijkml** [comment]
Sure, that sounds great! If you have the time during the week, please go ahead and take care of it. Thank you!

**Comment by ijkml** [comment]
Hi @Velka-DEV
I understand you might be busy, so if you haven't had a chance to tackle this yet, don't worry. I've got some free time and would be happy to take care of this, if that works for you.

**Comment by Velka-DEV** [comment]
Hi @ijkml,

Yeah sorry i'm quite busy these days. If you have the time, go ahead it's good for me.

If not, i will handle that but when i got some time.

**Comment by ijkml** [comment]
Thank you, and no, it's no problem at all.

**Pull request merged**
